# Generated by Django 5.0.6 on 2024-07-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quechua', models.CharField(max_length=50)),
                ('espanol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
